--------------------------------------------------------
--  Fichier créé - mardi-novembre-09-2021   
--------------------------------------------------------
DROP TABLE "ABDO"."CLIENT" cascade constraints;
DROP TABLE "ABDO"."ACHETER" cascade constraints;
DROP TABLE "ABDO"."EMPLOYÉES" cascade constraints;
DROP TABLE "ABDO"."EQUIPMENTS" cascade constraints;
DROP TABLE "ABDO"."TICKETS" cascade constraints;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "ABDO"."CLIENT" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(20 BYTE), 
	"AGE" VARCHAR2(20 BYTE), 
	"ID_EMPLOYEE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ACHETER
--------------------------------------------------------

  CREATE TABLE "ABDO"."ACHETER" 
   (	"ID_TICKET" NUMBER(*,0), 
	"ID_CLIENT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYÉES
--------------------------------------------------------

  CREATE TABLE "ABDO"."EMPLOYÉES" 
   (	"ID_EMPLOYÉE" NUMBER(*,0), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"SALAIRE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPMENTS
--------------------------------------------------------

  CREATE TABLE "ABDO"."EQUIPMENTS" 
   (	"ID_EQUIPMENT" VARCHAR2(20 BYTE), 
	"NOM_EQUIPMENT" VARCHAR2(20 BYTE), 
	"PRIX_EQUIPMENT" FLOAT(126), 
	"PANNE" VARCHAR2(20 BYTE), 
	"ID_EMPLOYÉE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TICKETS
--------------------------------------------------------

  CREATE TABLE "ABDO"."TICKETS" 
   (	"ID_TICKET" NUMBER(*,0), 
	"PRIX_TICKET" FLOAT(126), 
	"DATE_VENTE" DATE, 
	"TYPE_TICKET" VARCHAR2(20 BYTE), 
	"ID_EMPLOYÉE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ABDO.CLIENT
SET DEFINE OFF;
Insert into ABDO.CLIENT (ID,NOM,PRENOM,MAIL,AGE,ID_EMPLOYEE) values ('2','b','a','c','12',null);
Insert into ABDO.CLIENT (ID,NOM,PRENOM,MAIL,AGE,ID_EMPLOYEE) values ('1','Q','S','D','12',null);
REM INSERTING into ABDO.ACHETER
SET DEFINE OFF;
REM INSERTING into ABDO."EMPLOYÉES"
SET DEFINE OFF;
REM INSERTING into ABDO.EQUIPMENTS
SET DEFINE OFF;
REM INSERTING into ABDO.TICKETS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABDO"."ID" ON "ABDO"."CLIENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ID_EMPLOYÉE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABDO"."ID_EMPLOYÉE" ON "ABDO"."EMPLOYÉES" ("ID_EMPLOYÉE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EQUIPMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABDO"."EQUIPMENTS_PK" ON "ABDO"."EQUIPMENTS" ("ID_EQUIPMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TICKETS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABDO"."TICKETS_PK" ON "ABDO"."TICKETS" ("ID_TICKET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "ABDO"."CLIENT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ABDO"."CLIENT" ADD CONSTRAINT "ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYÉES
--------------------------------------------------------

  ALTER TABLE "ABDO"."EMPLOYÉES" ADD CONSTRAINT "ID_EMPLOYÉE" PRIMARY KEY ("ID_EMPLOYÉE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABDO"."EMPLOYÉES" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "ABDO"."EMPLOYÉES" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ABDO"."EMPLOYÉES" MODIFY ("ID_EMPLOYÉE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPMENTS
--------------------------------------------------------

  ALTER TABLE "ABDO"."EQUIPMENTS" ADD CONSTRAINT "EQUIPMENTS_PK" PRIMARY KEY ("ID_EQUIPMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABDO"."EQUIPMENTS" MODIFY ("NOM_EQUIPMENT" NOT NULL ENABLE);
  ALTER TABLE "ABDO"."EQUIPMENTS" MODIFY ("ID_EQUIPMENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TICKETS
--------------------------------------------------------

  ALTER TABLE "ABDO"."TICKETS" ADD CONSTRAINT "TICKETS_PK" PRIMARY KEY ("ID_TICKET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABDO"."TICKETS" MODIFY ("ID_TICKET" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "ABDO"."CLIENT" ADD CONSTRAINT "FK_ID_EMPLYEE" FOREIGN KEY ("ID_EMPLOYEE")
	  REFERENCES "ABDO"."EMPLOYÉES" ("ID_EMPLOYÉE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACHETER
--------------------------------------------------------

  ALTER TABLE "ABDO"."ACHETER" ADD CONSTRAINT "ID_CLIENT" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "ABDO"."CLIENT" ("ID") ENABLE;
  ALTER TABLE "ABDO"."ACHETER" ADD CONSTRAINT "ID_TICKET" FOREIGN KEY ("ID_TICKET")
	  REFERENCES "ABDO"."TICKETS" ("ID_TICKET") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EQUIPMENTS
--------------------------------------------------------

  ALTER TABLE "ABDO"."EQUIPMENTS" ADD CONSTRAINT "ID_EMPLOYÉE_2" FOREIGN KEY ("ID_EMPLOYÉE")
	  REFERENCES "ABDO"."EMPLOYÉES" ("ID_EMPLOYÉE") ENABLE;
